"""Render and build the SCAN image — the container the scan itself runs in.

Phase 2 builds ``vash-env-<target>``: the target's own environment, with its
toolchain and dependencies installed. But the scan has always run in
``vash:latest`` (python-slim + node), which has **none** of that. The
consequences were not theoretical — they were measured against real targets:

  * ``javac``/``java``/``mvn``/``go``/``dotnet``/``strace`` are all absent, so
    every non-Python PoC recipe dies at ``command not found``;
  * there is no docker CLI and no docker socket in the scan container, so it
    cannot reach the provisioned image either (and giving it the socket would
    be root-equivalent on the host — that is not an option for a tool whose
    whole claim is safe isolation);
  * even Python only *appeared* to work, because the handful of target imports
    that succeeded (``yaml``, ``pydantic``) happened to be VASH's OWN
    dependencies. A target needing ``flask`` or ``requests`` had nothing.

So this module inverts the layering: instead of teaching the scan container
about every ecosystem, it puts **VASH inside the provisioned image**. The
container that hunts becomes the container the target actually needs, and a PoC
can compile, link and import the real thing.

Text generation + a `docker build`; nothing here executes target code.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

from vash.provision.build import (
    DEFAULT_BUILD_TIMEOUT,
    CommandResult,
    DockerClient,
    SubprocessDocker,
    _TAG_SAFE,
    _tail,
)

log = logging.getLogger(__name__)

# The VASH source tree that gets installed into the image (this repo).
VASH_SOURCE_ROOT = Path(__file__).resolve().parent.parent.parent

# Where VASH's own virtualenv lives inside the scan image. Deliberately NOT on
# PATH — see the note in the rendered Dockerfile.
VENV = "/opt/vashvenv"


def scan_image_tag_for(repo_path: Path) -> str:
    """Deterministic tag for a target's scan image."""
    name = _TAG_SAFE.sub("-", Path(repo_path).name.lower()).strip("-.") or "target"
    return f"vash-scan-{name}:latest"


# The paths COPY'd out of the VASH source tree. Mirrors the top-level Dockerfile
# so the two cannot drift into installing different things.
_VASH_PAYLOAD = [
    ("pyproject.toml README.md", "./"),
    ("vash", "./vash"),
    ("prompts", "./prompts"),
    ("schemas", "./schemas"),
    ("config", "./config"),
    ("bench", "./bench"),
    ("licenses", "./licenses"),
    ("NOTICE LICENSE", "./"),
]

# Create VASH's venv. The provisioned base may be python:3.11-slim (python +
# working venv), node:20 or golang:1.22 (Debian: a python3.11 whose `venv` is
# BROKEN until the separate python3-venv package is installed), or
# maven:3.9-eclipse-temurin-21 (no python at all).
#
# The probe therefore ATTEMPTS A THROWAWAY VENV rather than merely checking the
# version — observed on node:20, where `python3 -c 'sys.version_info >= (3,11)'`
# passes and `python3 -m venv` then fails with "you need to install the
# python3-venv package", taking the fast path straight into a build error.
# uv is the universal fallback: it installs a private 3.11 with no distro
# package and no root.
_VENV_SETUP = f"""RUN set -eu; \\
    if command -v python3 >/dev/null 2>&1 \\
       && python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)' \\
       && python3 -m venv /tmp/vash-venv-probe >/dev/null 2>&1; then \\
        rm -rf /tmp/vash-venv-probe; \\
        python3 -m venv {VENV}; \\
        {VENV}/bin/pip install --no-cache-dir -e /app; \\
    else \\
        rm -rf /tmp/vash-venv-probe; \\
        curl -LsSf https://astral.sh/uv/install.sh | sh; \\
        export PATH="/root/.local/bin:$PATH"; \\
        uv python install 3.11; \\
        uv venv --python 3.11 {VENV}; \\
        uv pip install --python {VENV}/bin/python --no-cache -e /app; \\
    fi"""

# The claude CLI is an npm package and the agent SDK shells out to it, so node
# is required even when the target ecosystem is not JavaScript.
_NODE_SETUP = """RUN set -eu; \\
    if ! command -v node >/dev/null 2>&1; then \\
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -; \\
        apt-get install -y --no-install-recommends nodejs; \\
    fi; \\
    npm install -g @anthropic-ai/claude-code; \\
    rm -rf /var/lib/apt/lists/*; \\
    claude --version"""


def render_scan_dockerfile(base_image: str) -> str:
    """Dockerfile text for a scan image layered on ``base_image``.

    ``base_image`` is normally the Phase 2 ``vash-env-<target>`` image, but any
    image the target builds in works.
    """
    copies = "\n".join(f"COPY {src} {dst}" for src, dst in _VASH_PAYLOAD)
    return f"""# GENERATED BY VASH (vash/provision/scan_image.py) — do not edit by hand.
# The scan container IS the target's environment: this layers VASH on top of the
# provisioned image so PoCs compile, link and import the real target.
FROM {base_image}

# git: recon's read-only history mining. build-essential/curl: graphify + wheels.
# strace: the observer for compiled languages (Go) — a compiled binary has no
# in-process hook, so evidence has to be taken at the syscall boundary. Absent
# from every base image we build on, and without it Go PoCs run with no
# observer at all. It still needs CAP_SYS_PTRACE at RUN time (see
# scripts/run-in-docker.sh); the observer's available_check tests for both.
RUN apt-get update && apt-get install -y --no-install-recommends \\
        git build-essential curl ca-certificates strace \\
    && rm -rf /var/lib/apt/lists/*

{_NODE_SETUP}

WORKDIR /app
{copies}

{_VENV_SETUP}

# *** LOAD-BEARING: VASH's venv is deliberately NOT added to PATH. ***
# If it were, `python3` inside the container would resolve to VASH's own
# interpreter, where the TARGET's code and dependencies are invisible — every
# Python PoC would fail to import the very thing it is meant to exploit (this
# was observed: `import app.reports` -> ModuleNotFoundError, while the target's
# own interpreter imported it fine). VASH is invoked by absolute path so that
# `python3`, `node`, `java`, `go` ... all remain the TARGET's toolchain.
ENV VASH_SANDBOX=1
# Tells the running scan that it is executing INSIDE the target's provisioned
# environment — the toolchain and the target's dependencies are already present.
# Without this the pipeline reports provisioning as merely "planned", and the
# hunter cannot tell whether deps_hint's "the target is installed, just import
# it" is actually true here.
ENV VASH_SCAN_IMAGE={base_image}
ENTRYPOINT ["{VENV}/bin/vash"]
CMD ["--help"]
"""


@dataclass
class ScanImageResult:
    status: str = "skipped"          # built | failed | skipped
    tag: str | None = None
    base_image: str | None = None
    dockerfile: str | None = None
    exit_code: int | None = None
    log_tail: str = ""
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        from dataclasses import asdict
        return asdict(self)


def build_scan_image(
    repo_path: Path,
    *,
    base_image: str,
    client: DockerClient | None = None,
    tag: str | None = None,
    vash_source: Path | None = None,
    timeout: int = DEFAULT_BUILD_TIMEOUT,
) -> ScanImageResult:
    """Build ``vash-scan-<target>`` from ``base_image`` + this VASH checkout.

    Fail-soft: a failure is reported, never raised — the caller degrades to the
    generic sandbox image rather than losing the run.
    """
    result = ScanImageResult(
        base_image=base_image, tag=tag or scan_image_tag_for(repo_path)
    )
    dockerfile = render_scan_dockerfile(base_image)
    result.dockerfile = dockerfile

    client = client or SubprocessDocker()
    if not client.available():
        result.status = "skipped"
        result.notes.append("docker unavailable — scan image not built")
        return result

    # NOTE: the build context is the VASH source tree (that is what gets
    # installed), NOT the target repo — the target is already baked into
    # base_image by Phase 2.
    context = Path(vash_source or VASH_SOURCE_ROOT)
    r: CommandResult = client.build(
        context=context, dockerfile=dockerfile, tag=result.tag, timeout=timeout
    )
    result.exit_code = r.exit_code
    result.log_tail = _tail(r.log, 2000)
    if r.ok:
        result.status = "built"
        result.notes.append(
            f"scan image {result.tag} = {base_image} + VASH "
            "(PoCs now run in the target's own environment)"
        )
        log.info("[provision] scan image built: %s (from %s)", result.tag, base_image)
    else:
        result.status = "failed"
        result.notes.append(
            f"scan image build failed (exit {r.exit_code}) — the scan can still "
            "run in the generic sandbox, but PoCs will not have the target's "
            "toolchain or dependencies"
        )
        log.warning("[provision] scan image build failed (exit %d)", r.exit_code)
    return result
